pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),

]

radarfine_consultants/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls',namespace='pages'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render, HttpResponse
from .counties import counties


def index(request):

    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')


def services(request):
    return render(request, 'pages/services.html')


def contact(request):
    return render(request, 'pages/contacts.html', {'counties': counties})

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!--fonts-->
    <link rel="stylesheet" href="{%static 'css/all.css'%}" />
    <!--bootstrap-->
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}" />
    <!--custom css-->
    <link rel="stylesheet" href="{%static 'css/style.css'%}" />
    <!--lightbox-->
    <link rel="stylesheet" href="{%static 'css/lightbox.min.css'%}" />
    <title>Radarfine Consultants {%block title%} {%endblock%}</title>
  </head>
  <body id="home" data-spy="scroll" data-target="#main-nav">
    <!--topbar-->
    {% include 'partials/_topbar.html' %}

    <!--navbar-->
    {% include 'partials/_navbar.html' %}
    <!--Body content-->
    {%block content%} {%endblock%}
    <!--footer-->
    {% include 'partials/_footer.html' %}

    <script src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{%static 'js/lightbox.min.js'%}"></script>
    <script src="{%static 'js/popper.js'%}"></script>
    <script src="{%static 'js/main.js'%}"></script>
  </body>
</html>

templates/pages/contacts.html
{%extends 'base.html'%} {%load static%} {%block title%} | Contact Us{%endblock%}
{%block content%}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{%url 'pages:index'%}"> <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active">Contact Us</li>
      </ol>
    </nav>
  </div>
</section>

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white text-center">
            <h4><i class="fas fa-phone"></i> Contact Us</h4>
          </div>
          <div class="card-body">
            <form action="." method="POST">
              {%csrf_token%}

              <div class="form-group">
                <label for="company">Company Name</label>
                <input
                  type="text"
                  name="username"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                <input
                  type="email"
                  name="email"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label for="county">County</label>
                <select name="county" id="county" class="form-control">
                  {%for county in counties %}
                  <option value="{{county}}">{{county}}</option>
                  {%endfor%}
                </select>
              </div>
              <div class="form-group">
                <label for="email">Message</label>
                <textarea name="message" id="" cols="50" rows="10"></textarea>
              </div>
              <input
                type="submit"
                value="SEND"
                class="btn btn-secondary btn-block"
              />
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}

templates/pages/index.html
{%extends 'base.html'%}
<!--static-->
{%load static%}
<!--title-->
{%block title%}|Home{%endblock%}
<!--content block-->
{%block content%}
<!--SHOWCASE-->
<section id="home_showcase">
  <div id="mycarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item carousel-image-1 active">
        <div class="container">
          <div class="carousel-caption text-left mb-5 text-danger">
            <h1 class="display-3">Branding</h1>
            <p class="lead"></p>
            <a href="{%url 'pages:services'%}" class="btn btn-info btn-lg">
              Learn More</a
            >
          </div>
        </div>
      </div>

      <div class="carousel-item carousel-image-2">
        <div class="container">
          <div class="carousel-caption text-left mb-5 text-danger">
            <h1 class="display-3">Marketing</h1>
            <p class="lead"></p>
            <a href="{%url 'pages:services'%}" class="btn btn-primary btn-lg">
              Learn More</a
            >
          </div>
        </div>
      </div>

      <div class="carousel-item carousel-image-3">
        <div class="container">
          <div class="carousel-caption text-left mb-5 text-danger">
            <h1 class="display-3">Consultancy</h1>
            <p class="lead"></p>
            <a href="{%url 'pages:services'%}" class="btn btn-secondary btn-lg">
              Learn More</a
            >
          </div>
        </div>
      </div>
    </div>
    <a href="#mycarousel" class="carousel-control-prev" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a href="#mycarousel" class="carousel-control-next" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
</section>

<!--HOME ICON SECTION  -->
<div class="container-fluid mt-5">
  <h1 class="text-center text-info" id="services">
    Try Radarfine Consultants And Taste Greatness
  </h1>
  <section id="home-icons" class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cog fa-3x mb-2 text-success"></i>
          <h3 class="text-success">Branding</h3>
          <p>
            Regardless of how classic your business is if you don't brand your
            products,they will remain in your warehouses.
          </p>
        </div>
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cloud fa-3x mb-2 text-info"></i>
          <h3 class="text-info">Marketing</h3>
          <p>
            At Radarfine we understand that Marketing is the cream of any
            organization.We thus don't leave anything to chance
          </p>
        </div>
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cart-plus fa-3x mb-2 text-secondary"></i>
          <h3 class="text-secondary">Consultancy</h3>
          <p>
            Decision Making is a core aspect in business. We help you make
            informed decisions for utmost Optimization.
          </p>
        </div>
      </div>
    </div>
  </section>

  <section id="vision" class="mb-2 bg-primary text-white">
    <div class="container">
      <h1 class="text-center text-success">Vision:</h1>
      <div class="row text-center">
        <div class="col">
          <div class="slider">
            <div>
              <blockquote class="blockquote">
                <p class="bold display-4">
                  To be a Creative Company For Excellence
                </p>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!--mission -->
  <section id="vision" class="mb-2 bg-info text-white">
    <div class="container">
      <h1 class="text-center text-primary">Mission:</h1>
      <div class="row text-center">
        <div class="col">
          <div class="slider">
            <div>
              <blockquote class="blockquote">
                <p class="mb-0 bold display-4">
                  To Magnify Brands
                </p>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- CONTACT -->
<section id="contact" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
        <h3>Get In Touch</h3>
        <p class="lead">Leave a Message, to help Us serve you better</p>
        <form action="." method="POST">
          {%csrf_token%}
          <div class="input-group input-group-lg mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-user"></i>
              </span>
            </div>
            <input
              type="text"
              class="form-control"
              placeholder="Name"
              required
            />
          </div>

          <div class="input-group input-group-lg mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-envelope"></i>
              </span>
            </div>
            <input
              type="email"
              class="form-control"
              placeholder="Email"
              required
            />
          </div>

          <div class="input-group input-group-lg mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-pencil-alt"></i>
              </span>
            </div>
            <textarea
              class="form-control"
              placeholder="Message"
              rows="20"
              required
            ></textarea>
          </div>

          <input
            type="submit"
            value="Submit"
            class="btn btn-primary btn-block btn-lg"
          />
        </form>
      </div>

      <div class="col-lg-3 align-self-center">
        <img src="{%static 'img/logo.jpg'%}" alt="" class="img-fluid" />
      </div>
    </div>
  </div>
</section>
{%endblock%}

templates/pages/services.html
{%extends 'base.html'%}
<!--static-->
{%load static%}
<!--title-->
{%block title%}|Home{%endblock%}
<!--content block-->
{%block content%}
<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{%url 'pages:index'%}"> <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active">Our Services</li>
      </ol>
    </nav>
  </div>
</section>

<!--HOME ICON SECTION  -->
<div class="container-fluid">
  <h1 class="text-center display-4 text-danger" id="services">
    What Radarfine Cosultants Do
  </h1>
  <section id="home-icons" class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cog fa-3x mb-2 text-success"></i>
          <h3 class="text-success">Branding</h3>
          <p>
            Regardless of how classic your business is if you don't brand your
            products,they will remain in your warehouses.
          </p>
        </div>
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cloud fa-3x mb-2 text-info"></i>
          <h3 class="text-info">Marketing</h3>
          <p>
            At Radarfine we understand that Marketing is the cream of any
            organization while products.We thus don't leave anything to chance
          </p>
        </div>
        <div class="col-md-4 mb-4 text-center">
          <i class="fas fa-cart-plus fa-3x mb-2 text-secondary"></i>
          <h3 class="text-secondary">Consultancy</h3>
          <p>
            Decision Making is a core aspect in business. We help you make
            informed decisions for utmost Optimization.
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- HOME HEADING SECTION -->
  <section id="home-heading" class="p-5 mb-5">
    <div class="dark-overlay">
      <div class="row">
        <div class="col">
          <div class="container pt-5">
            <h1>Radarfine adds Value:</h1>
            <p class="lead">
              Industry knowledge and referable relationships An intergrated
              package of services for executives
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="home-heading1" class="p-5 mb-5">
    <div class="dark-overlay">
      <div class="row">
        <div class="col">
          <div class="container pt-5">
            <h1>Management Tool Set</h1>
            <p class="lead">
              Motivation, delegation, self-awereness, communication, leadership
              and ownership attitude
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="home-heading2" class="p-5 mb-3">
    <div class="dark-overlay">
      <div class="row">
        <div class="col">
          <div class="container pt-5">
            <h1>Reload Program</h1>
            <p class="lead">
              In hard times, you must reload and get an energetic start-up
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{%endblock%}

templates/partials/_footer.html
<footer id="main-footer" class="bg-primary text-white py-5">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h5><i class="fas fa-plug"></i> Links</h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <a class="text-white" href="#home_showcase">Home</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="{%url 'pages:services'%}">Branding</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="{%url 'pages:services'%}">Marketing</a>
          </li>
        </ul>
      </div>
      <div class="col-sm-3">
        <h5><i class="fas fa-paper-plane"></i> Services</h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <a class="text-white" href="{%url 'pages:services'%}">Branding</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="{%url 'pages:services'%}">Marketing</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="{%url 'pages:services'%}"
              >Consultation</a
            >
          </li>
        </ul>
      </div>
      <div class="col-sm-3">
        <h5><i class="fas fa-map-marker"></i> Locate us</h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <a class="text-white" href="">Nanyuki</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="">Nyahururu</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="">Nakuru</a>
          </li>
        </ul>
      </div>
      <div class="col-sm-3">
        <h5><i class="fas fa-gavel"></i> Terms</h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <a class="text-white" href="">FAQ</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="">T&Cs</a>
          </li>
          <li class="my-1">
            <a class="text-white" href="">Is Radarfine in My County?</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="row mb-5">
      <div class="col-sm-12">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a class="nav-link text-white" href="tel:+254 797813829">
              <i class="fas fa-phone" aria-hidden="true"></i>
              +254 797813829
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link text-white"
              href="mailto:radarfineconsultants@gmail.com"
            >
              <i class="fas fa-envelope-open" aria-hidden="true"></i>
              radarfineconsultants@gmail.com
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white">
              <i class="fas fa-envelope" aria-hidden="true"></i>
              P.O Box 743-20300 Nyahururu
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="row text-center">
      <div class="col m-auto">
        <p class="lead text-center">
          Copyright &copy; <span id="year"></span> Radarfine Consultants
        </p>

        <small
          ><p>
            Designed and Developed by ||
            <strong
              ><a href="#" class="text-secondary"
                >UniCorn IT Solutions</a
              ></strong
            >
          </p></small
        >
      </div>
    </div>
  </div>
</footer>

templates/partials/_navbar.html
{%load static%}
<!--Navbar-->

<nav
  class="navbar navbar-expand-md navbar-dark bg-primary sticky-top"
  id="main-nav"
>
  <div class="container-fluid">
    <a href="{%url 'pages:index'%}" class="navbar-brand">
      <img
        src="{%static 'img/logo.jpg'%}"
        width="200"
        height="80"
        alt="Radarfine Consultants"
      />
     </h3>
    </a>
    <button
      class="navbar-toggler"
      data-toggle="collapse"
      data-target="#navbarCollapse"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav">
        <li 
        {% if "/" == request.path%}
                  class="nav-item active mr-3"
                  {%else%}
        class="nav-item mr-3"
        {%endif%}
        >
          
          <a href="{%url 'pages:index'%}" class="nav-link">
            <i class="fas fa-home"></i> Home</a
          >
        </li>
        <li 
        {% if "about" in request.path%}
                  class="nav-item active mr-3"
                  {%else%}
        class="nav-item mr-3"
        {%endif%}
        >
          <a href="{%url 'pages:about'%}" class="nav-link"> <i class="fas fa-users"></i> About Us</a>
        </li>
         <li 
        {% if "services" in request.path%}
                  class="nav-item active mr-3"
                  {%else%}
        class="nav-item mr-3"
        {%endif%}
        >
          <a href="{%url 'pages:services'%}" class="nav-link"> <i class="fas fa-book"></i> Our Services</a>
        </li>

         <li 
        {% if "contact" in request.path%}
                  class="nav-item active mr-3"
                  {%else%}
        class="nav-item mr-3"
        {%endif%}
        >
          <a href="{%url 'pages:contact'%}" class="nav-link">
            <i class="fas fa-phone"></i> Contact Us</a
          >
        </li>
      </ul>

      
    </div>
  </div>
</nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4"><i class="fas fa-phone"></i>+254 797813829</div>
      <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> radarfineconsultants@gmail.com
      </div>
      <div class="col-md-4">
        <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter mr-3"></i>
          </a>
          <a href="#">
            <i class="fab fa-facebook mr-3"></i>
          </a>

          <a href="#">
            <i class="fab fa-whatsapp mr-3"></i>
          </a>

          <a href="#">
            <i class="fab fa-linkedin mr-3"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram mr-3"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>